name: 🐛 Bug Report
description: Report a bug in UnwindTools.
title: "bug: "
labels: ["🐛 Bug"]
type: bug
body:
  - type: checkboxes
    attributes:
      label: Did you check these before submitting?
      description: Make sure you checked all of the below before submitting an issue
      options:
        - label: I have updated `UnwindTools` to the latest version before submitting this issue
          required: true
        - label: I have not read any of these steps, please close my issue when you see it.
          required: false
        - label: I have tested the issue while disabling all other addons
          required: true
  - type: input
    attributes:
      label: "UnwindTools Version"
      placeholder: "0.1.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Please include any related errors you see in BugSack.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
